export const handleTransactionType="HANDLE_TRANSACTION_TYPE"
export const handleDate="HANDLE_DATE"
export const handleDescription="HANDLE_DESCRIPTION"
export const handleAmount="HANDLE_AMOUNT"
export const handleAccountName="HANDLE_ACCOUNT_NAME"
export const addTransaction="ADD_TRANSACTION" 
export const getAccount="GET_ACCOUNTS"
export const editTransaction="EDIT_TRANSACTION"
